apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: se4ai-chatbot
  name: se4ai-chatbot-deployment
  labels:
    app: se4ai-chatbot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: se4ai-chatbot-app
  template:
    metadata:
      labels:
        app: se4ai-chatbot-app
    spec:
      containers:
<<<<<<< HEAD
      - name: se4ai-chatbot
        image: mmatkowi/se4ai-chatbot:1.2
        ports:
        - containerPort: 8501
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        env:
        - name: PINECONE_INDEX_NAME
          value: "se4ai-chatbot"
        - name: PINECONE_API_ENV
          value: "asia-southeast1-gcp-free"
        - name: BROWSER
          value: "chrome"
        - name: BROWSER_BINARY_LOCATION
          value: "/usr/bin/chromium"
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pinecone-api-key-secret
              key: pinecone-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key-secret
              key: openai-api-key
        - name: TRUBRICS_EMAIL
          valueFrom:
            secretKeyRef:
              name: trubrics-email-secret
              key: trubrics-email
        - name: TRUBRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trubrics-password-secret
              key: trubrics-password
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
=======
        - name: se4ai-chatbot
          image: mmatkowi/se4ai-chatbot:1.2
          ports:
            - containerPort: 8501
          env:
            - name: PINECONE_INDEX_NAME
              value: "se4ai-chatbot"
            - name: PINECONE_API_ENV
              value: "asia-southeast1-gcp-free"
            - name: BROWSER
              value: "chrome"
            - name: BROWSER_BINARY_LOCATION
              value: "/usr/bin/chromium"
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pinecone-api-key-secret
                  key: pinecone-api-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key-secret
                  key: openai-api-key
            - name: TRUBRICS_EMAIL
              valueFrom:
                secretKeyRef:
                  name: trubrics-email-secret
                  key: trubrics-email
            - name: TRUBRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trubrics-password-secret
                  key: trubrics-password
>>>>>>> 9c9bbfb7f965950f79199bb783ab10fdc884e469
